### ISSUE TITLE
No .d.ts files in output of ts_project

### ISSUE THREAD

**Issue by mariusziemke** [aspect-build/rules_ts#160]
Hi,

I am relatively new to Bazel and rules_ts, so maybe this is a user error as well, but when building my `ts_project`, only `js` and `js.map` are added to the outputs.

When using the `emit_declaration_only` option, `d.ts` files are correctly exported, but obviously no compiled javascript or source maps.

### Reproduce

Environment:
- rules_ts-1.0.0-rc3
- bazel 5.3.1

/BUILD
```
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "test",
    srcs = ["index.ts"],
    declaration = True
)
```

/tsconfig.json
```
{
  "compilerOptions": {
    "declaration": true,
  }
}
```

/index.ts
```
export const a: string = "123";
```

#### Build Output

```
INFO: Analyzed target //test:test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //test:test up-to-date:
  bazel-bin/test/index.js
  bazel-bin/test/index.js.map
```

As you can see only the `js` and `js.map` files are send to the output.

**Comment by jbedard** [comment]
Declarations are not part of the `DefaultInfo` since most consuming rules only need the js (see [`ts_project`](https://github.com/aspect-build/rules_ts/blob/v1.0.0-rc3/ts/private/ts_project.bzl#L226)). When they are needed they can be found in [`JsInfo(declaractions)`](https://github.com/aspect-build/rules_js/blob/v1.3.1/js/private/js_info.bzl#L6)

**Comment by mariusziemke** [comment]
Thanks for the clarification @jbedard! Using `ts_project` with `js_filegroup` solves the issue for me :-)
