### ISSUE TITLE
Gazelle extension for TypeScript

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/rules_ts#2]
Replaces https://github.com/aspect-build/rules_js/issues/20

**Comment by wtgtybhertgeghgtwtg** [comment]
I've been trying my hand at this, but it's fraught with speedbumps.
 - Gazelle requires extensions to be built in Go.  There [was talk](https://github.com/bazelbuild/rules_nodejs/issues/789#issuecomment-691563850) about a plugin to support other languages, but it seems to have stalled.
 - Since `esbuild` [doesn't expose its parser](https://github.com/evanw/esbuild/issues/201) and I can't seem to find any other parser in Go-space, I've been statically linking a Rust binary that uses `swc`.  Since `swc` has [a library to grab dependencies](https://crates.io/crates/swc_ecma_dep_graph), this part is surprisingly straightforward.
 - `rules_go` has issues with IDE support for `cgo`, so errors around the bindings on the Go side just have to be ignored.
 - The ecosystem does not have go-to rules for certain tasks like linting or formatting like other languages.  I've mostly had to resolve to some internal macros for those, but they are not portable.
Right now, I've got it far enough that it can spit out something like
```starlark
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("@npm_dependencies//:defs.bzl", "npm_link_all_packages")
load("//macros/eslint-test:eslint_test.bzl", "eslint_test")
load("//macros/transpile-typescript:transpile_typescript.bzl", "transpile_typescript")
 
npm_link_all_packages(name = "node_modules")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

transpile_typescript(
    name = "typescript",
    srcs = ["source/render-package-json.ts"],
    package_json = "package.json",
    tsconfig = ":tsconfig",
    deps = [":node_modules/sort-keys"],
)

npm_package(
    name = "render-package-json",
    srcs = [":typescript"],
    visibility = ["//visibility:public"],
)

eslint_test(
    name = "eslint_test",
    srcs = ["source/render-package-json.ts"],
    eslintrc = ".eslintrc.cjs",
    package_json = "package.json",
    tsconfig = ":tsconfig",
    deps = [":node_modules/sort-keys"],
)
```
but it's hacky and nowhere near close enough for a PR.  If the trade-offs above are acceptable for now, is there a design document I can conform to while cleaning it up and submit a proof of concept?

**Comment by alexeagle** [comment]
Hi @wtgtybhertgeghgtwtg you made some good progress there!

I'm sorry we didn't update this issue sooner - right now we are planning to make the gazelle extension licensed differently from rules_ts so that we have some way to pay our engineers.

It does use esbuild's parser, with a little trick to get at the needed API.

We have that in a private repo, are you interested in collaborating on it despite that?

**Comment by wtgtybhertgeghgtwtg** [comment]
Most of the work I have has been with `swc` and linking side of things, so I doubt I'd be of much use if you've found an `esbuild` setup.  Thank you for the offer, however.

**Comment by gregmagolan** [comment]
We are close to releasing this feature with the Aspect CLI. Closing this issue as we are developing it closed source in our monorepo.
