### ISSUE TITLE
[Bug]: JSON data from `ts_project` not found at runtime 

### ISSUE THREAD

**Issue by loudmouth** [aspect-build/rules_ts#250]
### What happened?

After discussion in the Bazel Slack in the `#javascript` channel, opening an issue here to track this apparent bug.

Given a a `ts_project` that resolves data as a "JSON module", when running a `js_binary` that depends on that `ts_project`, the JSON file is not found at runtime. The expected behavior is that the data would be included at runtime. It is also expected that the data be available at compile time since it may imported, not only by it's local package target, but by other `ts_project`s that depend on it.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `bazel 5.3.2`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:  `rules_ts-1.0.0-rc6`

Language(s) and/or frameworks involved: TypesScript, JavaScript

### How to reproduce

A branch reproducing the issue can be found here: https://github.com/loudmouth/bazel-rules_js-poc/tree/ts_project-data

Just try to running `bazel run //app/app-a:main` and the output will be: 

"Error: Cannot find module './data.json'"

```shell
├── BUILD.bazel
├── WORKSPACE
├── app
│   └── app-a
│       ├── BUILD.bazel
│       ├── index.ts
├── lib
│   ├── lib-a
│   │   ├── BUILD.bazel
│   │   ├── index.ts
│   ├── lib-data
│   │   ├── BUILD.bazel
│   │   ├── data.json
│   │   ├── index.ts
```

### Any other information?

Linking to the [Slack thread](https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1668518442533219) since there was already discussion as to (a) possible fix(es)

**Comment by gzm0** [comment]
I have been investigating this and it seems a similar issue happens with imported JS files (when `allow_js = True`).

I suspect they both have the same root cause (unverified at this point): ts_project seems to never declare input files as dependencies of its output. It seems to only ever declare new tsc outputs.

In other words, for each input it currently decides between the following two states:

- Needs to be declared as an output.
- Doesn't need to be declared as an output (nor a dependency)

IIUC we'd need to add the following state:

- Doesn't need to be declared as an output but as a dependency.

IMO this can most easily be seen between the following two lines:

https://github.com/aspect-build/rules_ts/blob/5ea2d011369bf371d2431871bd178d6893766392/ts/private/ts_project.bzl#L209

https://github.com/aspect-build/rules_ts/blob/5ea2d011369bf371d2431871bd178d6893766392/ts/private/ts_project.bzl#L242
 
==> all non-transitive JS sources must be default outputs.

This is blocking our migration to rules_ts, so I might spend some more time looking into this. Any pointers are appreciated.

**Comment by gzm0** [comment]
As a workaround: The json inputs can be added to the `assets` parameter (additionally) to make them available downstream.
