### ISSUE TITLE
[Bug]: Upgrading from JS 1.18 to 1.19 and TS 1.1.0 to 1.2.0 doesn't work

### ISSUE THREAD

**Issue by supercairos** [aspect-build/rules_ts#344]
### What happened?

When updrading I see this error:

```
ode_modules/.aspect_rules_js/@shadow+i18n@0.0.0/node_modules/@shadow/i18n/src/i18n.d.ts(2,29): error TS7016: Could not find a declaration file for module 'express'. '/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/express@4.18.2/node_modules/express/index.js' implicitly has an 'any' type.
  If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
node_modules/.aspect_rules_js/@shadow+log@0.0.0/node_modules/@shadow/log/src/pino.d.ts(2,25): error TS7016: Could not find a declaration file for module 'express'. '/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/express@4.18.2/node_modules/express/index.js' implicitly has an 'any' type.
  If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
```

### Version

Bazel 6.0.0
TS 1.2.0 to 1.3.3
JS 1.19.0 to 1.23.2

### How to reproduce

```shell
I have a monorepo with a package that use `express` library to setup the HTTP framework
I then have multiple services that use this package.

Before upgrading, express types were exported, but now It seams that the types are not exported anymore.

I've tried adding the `@types/express` to the bazel build file but didn't change anything.
```

**Comment by thesayyn** [comment]
it really hard to know what could be wrong here exactly just by looking at the error messages. would it be possible to provide a reproduction repo?

**Comment by supercairos** [comment]
@thesayyn Sorry for the late reply, but i've made a repository to show the issue :)

https://github.com/supercairos/repro-bazel-propagation

**Comment by supercairos** [comment]
Hi @thesayyn, any chance you had time to look a this issue ? 

I wish I could help but I don't really undestand how this bazel rules works :(
Let me know if I can be of any assistance :)

**Comment by jbedard** [comment]
This is because `@test/c` depends on `@types/express` and exposes express as part of its API, but `@types/express` is a dev dependency and does not get propagated forward. When `@test/a` is then compiling express is undeclared.

Enabling the `skipLibCheck` tsconfig option fixes this and is also recommended for performance reasons.

**Comment by jbedard** [comment]
Or you can also make `@types/express` a dependency (instead of dev-dependency) of `@test/c`. The `@types/express` are exposed as part of the `@test/c` types, so technically anything depending on `@test/c` at compile-time also depends on `@types/express` at compile-time. Unfortunately npm doesn't have the concept of "compile time deps" so this isn't ideal, but I think the same problem exists outside bazel as well.
